### ISSUE TITLE
Selecting exiting connection in JazzNrepl results in exception

### ISSUE THREAD

**Issue by aleksandersumowski** [clojure-vim/jazz.nvim#1]
`stack traceback:
^I...epos/github.com/clojure-vim/acid.nvim/lua/acid/utils.lua:90: in function 'ends_with'
^I...ithub.com/clojure-vim/acid.nvim/lua/acid/connections.lua:13: in function 'pwd_to_key'
^I...ithub.com/clojure-vim/acid.nvim/lua/acid/connections.lua:52: in function 'select'
^I...epos/github.com/clojure-vim/jazz.nvim/lua/jazz/nrepl.lua:259: in function 'handle'
^I...github.com/Vigemus/impromptu.nvim/lua/impromptu/init.lua:160: in function 'callback'`

Seems that ends_with is passed with a connection. And that seems to be caused by `pwd` being a connection due to some reason ...

**Comment by hkupty** [comment]
Hi, thanks for your issue.

This is really weird. I'll definitely look into it.

Does `JazzNrepl` works at least once when there's a connection (i.e. conn exists but not active)  or never works?

**Comment by aleksandersumowski** [comment]
Spawning new repl works, attempting to connect to existing external repl fails in the same way

**Comment by hkupty** [comment]
Thanks for the extra info.

I'll look into it.

**Comment by hkupty** [comment]
I believe the linked commit fixes the problem. Could you test that branch before I merge?

Cheers,
Henry

**Comment by aleksandersumowski** [comment]
I only had time to check now - seems to work. I'm having other issues - will report other issues
