### ISSUE TITLE
JazzFindUsages with no connection results in exception

### ISSUE THREAD

**Issue by aleksandersumowski** [clojure-vim/jazz.nvim#2]
Attempting to use `JazzFindUsages` prints:

`[Acid] No active connection to a nrepl session. Aborting

error caught in async handler '/Users//.cache/vimfiles/repos/github.com/clojure-vim/acid.nvim/rplugin/python3/acid:function:AcidSendNrepl [[{'id': '01D9GDZZ28TZ
RG0NS90AZQYPST', 'ns': 'feed.parse', 'symbol': '")', 'op': 'info'}]]'
Traceback (most recent call last):
  File "/Users//.cache/vimfiles/repos/github.com/clojure-vim/acid.nvim/rplugin/python3/acid/__init__.py", line 48, in acid_eval
    payload, addr = data
ValueError: not enough values to unpack (expected 2, got 1)`

then still displays interface with no usages listed

**Comment by hkupty** [comment]
I merged the PR that should fix this issue. If you still have any problems regarding either issues, feel free to reopen any or open a new one.

Thanks for the issue and for helping make jazz and clojure tooling in neovim better :)
